"""DB/columns.json（列の辞書）を作る。列の意味・単位・「なぜ取るか」を、ここに書く。

列を足したら、ここに書いてから `python DB/make_columns.py` で columns.json を作り直し、`python DB/build_db.py` で DB に反映する。
build_db.py は、columns.json に無い列、または実データに無い列があると警告する。
"""
import json
from pathlib import Path

H = Path(__file__).resolve().parent


def c(meaning, why, unit=""):
    return {"meaning": meaning, "why": why, "unit": unit}


COLUMNS = {
    "runs": {
        "description": "1実行 = 1つの設定 × プレイヤーを置く広告主1人。主キー run_id。params と結果はすべて run_id で結ぶ。",
        "columns": {
            "run_id": c("実行の ID。`R{設定とコードの版のハッシュ}-p{プレイヤー位置}`。同じ設定を同じコードで流すと同じ値になる",
                        "どのパラメータでどの結果が出たかを、run_id 1本で結ぶため"),
            "spec_name": c("spec.json の name（人が付けた名前）", "人が読むときの目印"),
            "work": c("作業ID（例 W001）", "どの作業の実験かを逆引きするため"),
            "rep": c("REP の ID（例 REP001）", "どの検証・探索の実験かを逆引きするため"),
            "note": c("spec.json の note", "実験意図の自由記述"),
            "sweep_point": c("sweep で振ったパラメータ名と値（JSON）", "パラメータ掃引の結果を、振った値で集計するため"),
            "player_index": c("プレイヤー戦略を置いた広告主の番号（0..47）。広告主ごとに予算・CPA・カテゴリが違う",
                              "位置による有利不利（予算規模、CPA制約の厳しさ）を切り分けるため"),
            "strategy": c("プレイヤー戦略（PID / ABid / OnlineLP / BC / IQL / CQL / BCQ / TD3_BC）", "手法ごとの比較の軸"),
            "model_id": c("学習ベースの戦略で、自前で学習した重みを使ったときの重みの ID（DB/models/<model_id>/）。同梱の重み・ルールベースは NULL",
                          "どの学習（データ・ステップ数・乱数）の重みで出た結果かを、models 表と結ぶため"),
            "model_dir": c("重みのフォルダ（リポジトリ直下からの相対パス）。同梱の重み・ルールベースは NULL", "重みの原本への逆引き"),
            "model_sha1": c("重みのファイル（.pth）の SHA-1", "同じ model_id でも中身が同じかを確かめるため"),
            "model_step_num": c("重みの学習ステップ数", "学習の長さで結果を分けて見るため", "ステップ"),
            "model_spec_name": c("重みを作った学習の spec の name", "人が読むときの目印"),
            "created_at": c("実行日時（ローカル時刻）", "時系列の把握"),
            "head_commit": c("実行時の git HEAD のコミットID", "あとから同じコードを取り出して再現するため"),
            "github_tree": c("実行時の github/ ディレクトリの tree ハッシュ", "シミュレータ本体のコードの版。変わったときだけ変わる"),
            "github_dirty": c("github/ に未コミットの変更があったか", "true の run は、コミットから再現できない。結果の扱いに注意するため"),
            "github_version": c("github_tree（＋未コミット差分のハッシュ）。run_id の元になる", "コードの版が違う結果を取り違えないため"),
            "repo_dirty_paths": c("実行時に未コミットだったパス（JSON、最大30件）", "再現できない変更の把握"),
            "host": c("実行した端末名", "端末差（浮動小数・乱数の実装差）の切り分け"),
            "os": c("OS", "同上"),
            "cpu_count": c("論理CPU数", "所要時間の解釈（並列実行数との関係）"),
            "status": c("ok / error", "失敗した run も記録して、欠測の理由を残すため"),
            "error": c("status=error のときの例外", "失敗の原因"),
            "traceback": c("status=error のときのトレースバック", "失敗の原因"),
            "python": c("Python のバージョン", "再現条件"),
            "numpy": c("numpy のバージョン", "再現条件（乱数列の実装差）"),
            "torch": c("torch のバージョン", "再現条件"),
            "pandas": c("pandas のバージョン", "再現条件"),
            "score": c("論文・コンペ式のスコア。エピソード報酬×CPAペナルティを全エピソードで足し、20000 で割った値",
                       "論文・コンペの評価指標そのもの。他の論文結果との比較に使う"),
            "reward_total": c("全エピソードの獲得価値（コンバージョン数）の合計", "ペナルティ前の生の成果。ペナルティの効きを見るため"),
            "sim_seconds": c("シミュレーション全体の所要時間", "実験規模の見積り（1回の評価にかかる時間）", "秒"),
            "wall_seconds": c("run 全体の所要時間（環境構築・集計・書き出しを含む）", "同上", "秒"),
            "peak_rss_mb": c("プロセスの最大メモリ（RSS）", "並列数を決める・規模を上げられるかの見積り", "MB"),
            "bidding_seconds_total": c("プレイヤーの bidding() の所要時間の合計", "「1回の思考にかかる時間」。手法の計算コストの比較", "秒"),
            "bidding_seconds_per_call_mean": c("bidding() 1回あたりの平均所要時間", "同上。コンペの制限時間（2秒）との比較", "秒"),
            "n_episodes": c("評価したエピソード数", "score の解釈（エピソード数で和をとる）"),
            "n_ticks": c("1エピソードのティック数", "同上"),
            "params_spec": c("spec.json（展開後。人が書いた『変えた値』）をそのまま JSON で", "人が意図した条件の原本"),
            "params_effective": c("実際に使われた値（コード側の既定値を補ったもの）を JSON で", "既定値に頼った値も含めて、どの設定の結果かを完全に特定するため"),
            "spec_file": c("展開前の spec.json のパス", "原本のファイルへの逆引き"),
        },
    },
    "episodes": {
        "description": "1実行 × エピソード。プレイヤーのエピソード全体の成績。主キー (run_id, episode)。",
        "columns": {
            "run_id": c("runs.run_id", "結合キー"),
            "episode": c("エピソード番号。広告機会の生成と環境ノイズの乱数シードになる", "同じ番号なら同じ広告機会列。手法間の比較は同じ episode で行う"),
            "category": c("プレイヤーの広告主のカテゴリ（0..5）", "カテゴリごとに価値の水準・競合が違うため"),
            "cpa_constraint": c("CPA 制約（1コンバージョンに使ってよい費用の上限）", "ペナルティの判定。位置ごとに 60..130 と違う"),
            "budget": c("予算", "予算消化率の分母。位置ごとに 2000..4850 と違う"),
            "reward": c("獲得価値（コンバージョン数の合計）", "最大化したい成果"),
            "all_cost": c("支払い合計", "予算消化・CPAの計算"),
            "real_cpa": c("実績 CPA = all_cost / reward", "CPA 制約との比較（超過するとペナルティ）"),
            "penalty": c("CPA 超過ペナルティ係数（超過なしは 1。超過すると (制約CPA/実績CPA)^beta）", "reward の何割がペナルティで失われたかを見るため"),
            "score_component": c("penalty × reward（20000 で割る前のスコア）", "エピソード単位のスコア"),
            "score_rank": c("48人の広告主の score_component の中でのプレイヤーの順位（1が最良）", "背景の広告主に対して強いか弱いかの絶対的な目安"),
            "n_agents": c("エピソードの広告主数", "順位の分母"),
            "all_compete_pv": c("競争に参加した広告機会の総数", "規模の把握"),
            "all_win_pv": c("露出まで到達した広告機会の数", "勝てた量"),
            "win_pv_ratio": c("露出数 / 競争数", "入札の積極性の目安"),
            "budget_consumer_ratio": c("予算消化率 = all_cost / budget", "予算を使い切れているか（使い切れていないなら入札が弱すぎる）"),
            "second_price_ratio": c("支払い / 勝った入札額の合計", "第2価格オークションなので、入札を上げても支払いがどれだけ増えるかの目安"),
            "cpa_exceedance_rate": c("(実績CPA − CPA制約) / CPA制約。正なら超過", "どれだけ制約を破ったか"),
            "last_compete_tick_index": c("最後に露出に至ったティック番号", "予算が尽きた時刻の目安（47 なら最後まで残った）"),
            "bid_mean": c("入札額の平均", "入札の水準"),
            "others_score_mean": c("プレイヤー以外の47人の score_component の平均", "背景の広告主の成績。プレイヤーの変更が他者に与える影響や、環境の難しさの目安"),
        },
    },
    "ticks": {
        "description": "1実行 × エピソード × ティック（48区間）。プレイヤー視点の時系列。主キー (run_id, episode, tick)。",
        "columns": {
            "run_id": c("runs.run_id", "結合キー"),
            "episode": c("エピソード番号", "結合キー"),
            "tick": c("ティック番号（0..47）。1エピソードを48区間に分けた時刻", "時間方向の挙動（予算ペース配分、競合の変化）を見るため"),
            "num_pv": c("そのティックの広告機会の数（トラフィック量）", "ティックの重み。トラフィックが多い時間帯に予算をどう配分したかの解釈に必要"),
            "pvalue_mean": c("プレイヤーにとっての pValue（コンバージョン確率の予測）の平均", "広告機会の価値の水準。入札額 = alpha × pValue"),
            "pvalue_std": c("同・標準偏差", "価値のばらつき。ばらつきが大きいほど、選別入札の余地が大きい"),
            "pvalue_sigma_mean": c("pValue の不確実性（sigma）の平均", "予測の不確実性が成績に効くかを後で検討するため"),
            "bid_mean": c("プレイヤーの入札額の平均", "入札の水準"),
            "bid_nonzero_ratio": c("入札額が正の広告機会の割合", "予算切れ・入札停止の検出"),
            "alpha_eff": c("実効入札係数 = 入札額の和 / pValue の和", "エージェントが決めるのは alpha だけ（論文の整理）なので、手法の違いは alpha の時系列に現れる。手法の挙動を見る主指標"),
            "alpha_rank": c("48人の alpha_eff の中でのプレイヤーの順位（1が最大）", "他者に対して強気か弱気か。勝てない原因が alpha の低さかを切り分ける"),
            "alpha_others_mean": c("他の47人の alpha_eff の平均", "競合の入札水準。プレイヤーの alpha との差が勝敗を決める"),
            "alpha_others_median": c("他の47人の alpha_eff の中央値", "外れ値（極端な alpha の競合）に引きずられない競合水準"),
            "n_won": c("落札した広告機会の数（スロット1〜3）", "勝てた量（露出の抽選前）"),
            "n_slot1": c("スロット1で落札した数", "露出率が高い（1.0）スロットをどれだけ取れたか"),
            "n_slot2": c("スロット2で落札した数", "露出率 0.8"),
            "n_slot3": c("スロット3で落札した数", "露出率 0.6"),
            "n_exposed": c("実際に露出した数（抽選後）", "コスト・価値が発生する単位"),
            "reward": c("そのティックの獲得価値", "成果の時間推移"),
            "cost": c("そのティックの支払い", "予算ペース配分の時間推移"),
            "remaining_budget_before": c("そのティックの入札前の残り予算", "予算の残り方（早く尽きるか、余るか）"),
            "lwc_mean": c("最下位スロット（3位）の最低落札価格の平均（least winning cost）", "市場価格の水準。競争の激しさの目安"),
            "total_cost_all": c("全広告主の支払い合計", "市場全体の消化量。他者がどの時刻に予算を使うか"),
            "n_active_agents": c("そのティックで予算が残っている広告主の数（最大48）", "時間とともに競合が脱落していく様子。競合の減少は alpha を下げるべき根拠になりうる"),
            "bidding_seconds": c("プレイヤーの bidding() の所要時間", "1回の思考にかかる時間", "秒"),
            "tick_wall_seconds": c("そのティックのシミュレーション全体の所要時間", "規模の見積り", "秒"),
            "rss_mb": c("そのティックでのメモリ使用量", "規模を上げられるかの見積り", "MB"),
        },
    },
    "agents": {
        "description": "1実行 × エピソード × 広告主（48人）。背景の広告主を含む全員の成績。主キー (run_id, episode, agent_index)。",
        "columns": {
            "run_id": c("runs.run_id", "結合キー"),
            "episode": c("エピソード番号", "結合キー"),
            "agent_index": c("広告主の番号（0..47）", "結合キー"),
            "agent_name": c("戦略名＋番号（背景の学習済み戦略 IQL/TD3_BC/CQL/BC/BCQ/MOPO/COMBO、OnlineLP、PID）", "背景の広告主の種類ごとの成績を比べるため"),
            "category": c("カテゴリ（0..5）", "カテゴリ単位の集計"),
            "budget": c("予算", "予算規模での比較"),
            "cpa_constraint": c("CPA 制約", "制約の厳しさでの比較"),
            "reward": c("獲得価値", "成果"),
            "cost": c("支払い合計", "予算消化"),
            "final_remaining_budget": c("エピソード終了時の残り予算", "使い切れたか"),
            "real_cpa": c("実績 CPA", "制約との比較"),
            "penalty": c("CPA 超過ペナルティ係数", "同上"),
            "score_component": c("penalty × reward", "スコア"),
            "score_rank": c("48人の中での順位（1が最良）", "プレイヤーの相対位置"),
            "is_player": c("プレイヤー戦略を置いた広告主か", "プレイヤーと背景の区別"),
        },
    },
    "models": {
        "description": "学習した重み 1 つ = 1 行（DB/models/<model_id>/meta.json）。主キー model_id。runs.model_id で評価の結果と結ぶ。",
        "columns": {
            "model_id": c("重みの ID。`M{手法・ステップ数・乱数シード・学習データのSHA-1・コードの版のハッシュ}`", "どの学習で出来た重みかを 1 本で結ぶため"),
            "spec_name": c("学習の spec.json の name", "人が読むときの目印"),
            "work": c("作業ID", "どの作業の学習かを逆引きするため"),
            "rep": c("REP の ID", "どの検証・探索の学習かを逆引きするため"),
            "note": c("spec.json の note", "学習の意図の自由記述"),
            "sweep_point": c("sweep で振った値（JSON）", "振った値で重みを選ぶため"),
            "algo": c("学習した手法（BC / IQL / CQL / BCQ / TD3_BC）", "手法ごとの比較の軸"),
            "step_num": c("学習ステップ数（1 ステップ = バッチ 100 件の更新 1 回）", "学習の長さで結果を分けて見るため", "ステップ"),
            "step_num_is_default": c("step_num が本家の既定値（BC・IQL は 20000、CQL・BCQ・TD3_BC は 100）か", "「本家の既定のまま」の重みを選ぶため"),
            "seed": c("random / numpy / torch の乱数シード", "再現のため。シードを変えた重みのばらつきを見るため"),
            "train_data": c("学習データ（rlData）のパス（リポジトリ直下から）", "どのデータで学習したか"),
            "train_data_sha1": c("学習データのファイルの SHA-1", "データが同じものかを確かめるため"),
            "spec_file": c("展開前の spec.json のパス", "原本への逆引き"),
            "created_at": c("学習した日時", "時系列の把握"),
            "head_commit": c("学習時の git HEAD", "同じコードを取り出して再現するため"),
            "github_tree": c("学習時の github/ の tree ハッシュ", "学習コードの版"),
            "github_dirty": c("github/ に未コミットの変更があったか", "true の重みはコミットから再現できない"),
            "github_version": c("github_tree（＋未コミット差分のハッシュ）。model_id の元になる", "コードの版が違う重みを取り違えないため"),
            "repo_dirty_paths": c("学習時に未コミットだったパス（JSON）", "再現できない変更の把握"),
            "host": c("学習した端末名", "端末差の切り分け"),
            "os": c("OS", "同上"),
            "status": c("ok / error", "失敗した学習も記録に残すため"),
            "error": c("status=error のときの例外", "失敗の原因"),
            "traceback": c("status=error のときのトレースバック", "失敗の原因"),
            "python": c("Python のバージョン", "再現条件"),
            "numpy": c("numpy のバージョン", "再現条件"),
            "torch": c("torch のバージョン", "再現条件"),
            "pandas": c("pandas のバージョン", "再現条件"),
            "device": c("学習に使った装置（cpu / cuda）", "再現条件（装置で数値が変わりうる）"),
            "model_file": c("重みのファイル名（torch.jit）", "読み込むファイル"),
            "model_sha1": c("重みのファイルの SHA-1", "同じ条件の学習が同じ重みになったかを確かめるため"),
            "weights_sha1": c("重みのテンソルそのものの SHA-1（ファイルの SHA-1 は、重みが同じでも変わることがある）", "重みが同じかを確かめるため"),
            "threads": c("学習に使った torch のスレッド数", "再現条件（スレッド数で数値が変わりうる）"),
            "checkpoints": c("途中の重みを残した学習ステップ（JSON）", "学習の経過を見るため"),
            "is_checkpoint": c("この行が、学習の途中の重み（チェックポイント）か", "最後の重みと途中の重みを分けるため"),
            "parent_model_id": c("チェックポイントのもとの学習の model_id", "同じ学習の経過をまとめるため"),
            "n_loss_rows": c("loss.csv の行数（= 記録した学習ステップ数）", "学習が最後まで進んだかの確認", "行"),
            "loss_last10pct_mean": c("学習の最後の 10% のステップでの、損失の平均（JSON。手法ごとに項目が違う）", "学習が発散していないかの目安"),
            "loss_all_finite": c("損失が最後まで有限だったか", "学習の発散の検出"),
            "train_seconds": c("学習の所要時間（データの読み込みを含む）", "研究の規模感", "秒"),
        },
    },
    "params_long": {
        "description": "runs.params_effective を縦に展開したもの（build_db.py が作る）。パラメータ値で run を絞る・結合するときに使う。",
        "columns": {
            "run_id": c("runs.run_id", "結合キー"),
            "key": c("パラメータ名（例 player.kwargs.base_action, env.Controller.pv_num）", "どのパラメータか"),
            "value_json": c("値（JSON 文字列）", "任意の型の値を保持"),
            "value_num": c("値が数値ならその値。そうでなければ NULL", "数値パラメータでの集計・並べ替え"),
        },
    },
}

# =============================================================================
# 記録の形式の版 2（2026-10-10、T006「実験記録の全面拡充」）で足した列・表。
# 版 1 の run（2026-10-09 までの約 1,400 run）には無い（NULL、または表に行が無い）。何を、なぜ取るかの一覧は DB/記録の一覧.md
# =============================================================================
J = "結合キー"
COLUMNS["runs"]["columns"].update({
    "config_key": c("設定（player・episodes・seed・gin）だけのハッシュ。コードの版を含まない（build_db.py が作る）",
                    "コードの版が違う run（版 1 と版 2 など）で、同じ設定のものを結ぶため。run_id はコードの版で変わる"),
    "record_version": c("記録の形式の版。1 = 2026-10-09 まで、2 = T006 で拡充（build_db.py が、無い run に 1 を入れる）",
                        "どの列・表がある run かを見分けるため"),
    "record_level": c("記録の段（basic / standard / detail / full）。版 1 の run は NULL", "どの表（raw/ の機会ごとの記録など）がある run かを見分けるため"),
    "record_level_num": c("記録の段の数値（basic 0、standard 1、detail 2、full 3）", "「この段以上」で絞るため"),
    "started_at_epoch": c("開始時刻（UNIX 時刻）", "並列で流した run の重なりを調べるため", "秒"),
    "ended_at": c("終了日時（ローカル時刻）", "同上"),
    "pid": c("プロセス番号", "同じ時刻に流れた run の区別"),
    "n_workers": c("この run を流したときの並列数（--workers）", "所要時間は並列数で変わる（メモリ帯域の取り合い）ので、時間を比べるときにそろえるため"),
    "n_tasks_in_batch": c("同じ起動で流した run の数", "同上"),
    "cpu_model": c("CPU の型名", "端末差・所要時間の解釈"),
    "machine": c("CPU の種類（x86_64 など）", "端末差の切り分け"),
    "python_executable": c("Python の実行ファイル", "どの環境で流したか"),
    "argv": c("起動したコマンドの引数", "流し方の再現"),
    "loadavg1_start": c("開始時のロードアベレージ（1 分）", "他の処理と重なっていたか（所要時間の解釈）"),
    "loadavg5_start": c("開始時のロードアベレージ（5 分）", "同上"),
    "loadavg1_end": c("終了時のロードアベレージ（1 分）", "同上"),
    "env_threads": c("スレッド数・GPU・ハッシュの種の環境変数（JSON）", "再現条件（スレッド数で数値・時間が変わりうる）"),
    "torch_num_threads": c("torch のスレッド数", "同上"),
    "run_experiment_sha1": c("research/src/run_experiment.py の SHA-1", "記録のコードの版（github_tree には入らない）"),
    "lib_versions": c("scipy・gin・psutil・pyarrow・duckdb の版（JSON）", "再現条件（scipy は雑音の打ち切り正規分布を作る）"),
    "import_seconds": c("import にかかった時間", "所要時間の内訳", "秒"),
    "strategy_init_seconds": c("プレイヤーの戦略を作る時間（重みの読み込みを含む）", "同上", "秒"),
    "write_seconds": c("集計と parquet の書き出しの時間", "記録の重さ", "秒"),
    "hook_seconds_total": c("記録（tick_hook）にかかった時間の合計", "記録を足したことで、どれだけ遅くなったか", "秒"),
    "sim_cpu_seconds": c("シミュレーション全体の CPU 時間", "壁時計との差が、待ち（他の処理との取り合い）", "秒"),
    "cpu_seconds": c("run 全体の CPU 時間", "同上", "秒"),
    "cpu_user_seconds": c("CPU 時間（ユーザー）", "同上", "秒"),
    "cpu_system_seconds": c("CPU 時間（システム）", "メモリの確保・解放の重さ", "秒"),
    "bidding_seconds_all_total": c("全 48 社の bidding() の時間の合計", "所要時間の内訳（入札／環境／記録）", "秒"),
    "env_sim_seconds_total": c("simulate_ad_bidding の時間の合計（やり直しを含む）", "同上", "秒"),
    "adjust_seconds_total": c("adjust_over_cost（予算超過の入札の取り消し）の時間の合計", "同上", "秒"),
    "n_sim_iters_total": c("simulate_ad_bidding を呼んだ回数の合計（ティック数 + やり直しの回数）", "予算超過のやり直しが、どれだけ起きたか", "回"),
    "maxrss_mb": c("プロセスの最大メモリ（OS が数えた値。peak_rss_mb はティックの終わりに測った値の最大）", "並列数を決めるため", "MB"),
    "mem_total_mb": c("端末のメモリ", "並列数の解釈", "MB"),
    "mem_available_start_mb": c("開始時の空きメモリ", "メモリ不足の失敗の切り分け", "MB"),
    "mem_available_end_mb": c("終了時の空きメモリ", "同上", "MB"),
    "gin_file_sha1": c("github/config/test.gin の SHA-1", "設定ファイルが同じか"),
    "gin_config": c("実行前の gin の設定の全文", "設定の全文を残すため"),
    "gin_operative_config": c("実行後の gin の設定の全文（実際に使われた値だけ）", "同上"),
    "spec_file_sha1": c("spec.json の SHA-1", "spec を書き換えていないかの確認"),
    "seeds": c("乱数の種の一覧（JSON）：numpy・torch、エピソード番号、環境の露出・雑音／抽選、予算超過の取り消し、広告機会の生成", "再現条件を 1 か所で読むため"),
    "files": c("この run のファイルと、そのバイト数（JSON）", "容量の実測"),
    "bytes_total": c("この run のファイルの合計", "容量の見積もり", "バイト"),
    "bytes_raw": c("そのうち raw/（git 管理外）の合計", "同上", "バイト"),
})
COLUMNS["models"]["columns"].update({
    "train_kwargs": c("本家の学習関数に渡した追加の引数（spec の train_kwargs。例：BCQ の max_action）", "既定と違う条件で学習した重みを見分けるため"),
})
COLUMNS["episodes"]["columns"].update({
    "n_est": c("N_est：プレイヤーが落札して露出した機会の、推定価値（①）の和", "REP006 の E = cost / n_est / C、P = n_est / n_real。入札者が見積もった購入数", "件"),
    "n_real": c("N_real：同じ機会の、雑音を加えて 0〜1 に切った確率（②）の和", "REP006 の P、L = n_real / reward。環境にとっての購入数の期待値", "件"),
    "real_var": c("同じ機会の、②×(1−②) の和", "抽選の分散。z = (reward − n_real) / sqrt(real_var) が平均 0・標準偏差 1 に近いかを見る（REP006 集計5）"),
    "n_won": c("落札した機会の数（露出の抽選の前）", "露出率（all_win_pv / n_won）"),
    "n_bids_dropped": c("予算超過のやり直しで、0 にされた入札の数", "C5（予算超過の取り消し）が、どれだけ効いたか", "件"),
    "n_sim_iters": c("simulate_ad_bidding を呼んだ回数（48 + やり直しの回数）", "同上", "回"),
    "trunc_u1": c("プレイヤーの雑音の打ち切りの乱数 u1（下側の幅は −2×u1 標準偏差）", "C3：打ち切りが上下で対称でないことと、P の関係を調べるため"),
    "trunc_u2": c("同・u2（上側の幅は +2×u2 標準偏差）", "同上"),
    "budget_exhausted_tick": c("残り予算が min_remaining_budget を下回ったティック（下回らなければ −1）", "予算切れの時刻（last_compete_tick_index は「最後に露出したティック」で、意味が違う）"),
    "num_pv": c("そのエピソードの広告機会の総数", "規模"),
    "episode_wall_seconds": c("エピソードの所要時間（最初のティックの記録から、最後のティックの記録まで）", "時間の内訳", "秒"),
    "episode_cpu_seconds": c("同・CPU 時間", "同上", "秒"),
    "bidding_seconds": c("プレイヤーの bidding() の時間の合計", "同上", "秒"),
    "hook_seconds": c("記録にかかった時間の合計", "同上", "秒"),
})
_TICK_AGENT_COMMON = {
    "est_sum_exposed": c("露出した機会の、推定価値（①）の和", "N_est のティックごとの値。必ず取る（REP006 8.1）", "件"),
    "real_sum_exposed": c("露出した機会の、雑音を加えて 0〜1 に切った確率（②）の和", "N_real のティックごとの値。必ず取る", "件"),
    "real_var_exposed": c("露出した機会の、②×(1−②) の和", "抽選の分散。必ず取る"),
    "est_sum_won": c("落札した機会（露出の前）の、①の和", "露出の抽選が、買った機会の質を変えていないかの確認", "件"),
    "real_sum_won": c("落札した機会（露出の前）の、②の和", "同上", "件"),
    "real_sum_all": c("全機会の、②の和", "落札しなかった機会を含めた水準。買った機会の偏り（P が手法の選び方で決まるか）を見る", "件"),
    "real_var_all": c("全機会の、②×(1−②) の和", "同上"),
    "conv_draw_sum_all": c("全機会の、抽選（露出を掛ける前）の結果の和", "C6：抽選の乱数が毎ティック同じ種で作り直されることの影響を調べるため", "件"),
    "n_real_below0": c("雑音を加えた値が 0 未満だった機会の数（0 に切られる）", "C3：0〜1 への切り詰めが、どれだけ起きているか", "件"),
    "n_real_above1": c("雑音を加えた値が 1 を超えた機会の数（1 に切られる）", "同上", "件"),
    "n_exposed_slot1": c("枠 1 で露出した数", "枠ごとの露出率（1・0.8・0.6）と、枠 3 の取り消しの確認", "件"),
    "n_exposed_slot2": c("枠 2 で露出した数", "同上", "件"),
    "n_exposed_slot3": c("枠 3 で露出した数（枠 2 が露出しなければ、枠 3 も露出しない）", "同上", "件"),
    "cost_slot1": c("枠 1 での支払い", "どの枠で払っているか"),
    "cost_slot2": c("枠 2 での支払い", "同上"),
    "cost_slot3": c("枠 3 での支払い", "同上"),
    "bid_sum": c("入札額の和（予算超過の取り消しのあと）", "alpha_eff の分子"),
    "bid_sum_exposed": c("露出した機会の入札額の和", "支払い / これ = 第二価格による割引（second_price_ratio のティックごとの値）"),
    "bid_sum_won": c("落札した機会の入札額の和", "同上（露出の前）"),
    "bid_p10": c("入札額の 10% 点", "入札額の分布"),
    "bid_p50": c("入札額の中央値", "同上"),
    "bid_p90": c("入札額の 90% 点", "同上"),
    "bid_max": c("入札額の最大", "同上"),
    "alpha_internal": c("手法の内部の入札係数 α（PID の alpha、Online LP の上限を掛けたあとの α、学習ベースの方策の出力）。ABid は、入札額が α × 価値² なので、alpha_eff と単位が違う",
                        "alpha_eff（入札額の和 / 価値の和）は、予算超過の取り消しで下がる。手法が出した α そのものを見るため"),
    "remaining_budget_after": c("そのティックの支払いのあとの残り予算", "予算の残り方"),
    "n_bids_dropped": c("予算超過のやり直しで、0 にされた入札の数", "C5 の確認", "件"),
    "cost_first_iter": c("やり直しの前（1 回目）の支払い", "予算超過の取り消しで、支払いがどれだけ減ったか"),
    "over_cost_ratio_first": c("1 回目の、(支払い − 残り予算) / 支払い（超過していなければ 0）", "同上"),
}
COLUMNS["ticks"]["columns"].update({k: v for k, v in _TICK_AGENT_COMMON.items()})
COLUMNS["ticks"]["columns"].update({
    "est_sum_all": c("全機会の、①の和（= pvalue_mean × num_pv）", "落札しなかった機会を含めた水準", "件"),
    "reward_slot1": c("枠 1 での購入数", "枠ごとの成果", "件"),
    "reward_slot2": c("枠 2 での購入数", "同上", "件"),
    "reward_slot3": c("枠 3 での購入数", "同上", "件"),
    "pvalue_p10": c("推定価値の 10% 点", "機会の価値の分布"),
    "pvalue_p50": c("推定価値の中央値", "同上"),
    "pvalue_p90": c("推定価値の 90% 点", "同上"),
    "pvalue_max": c("推定価値の最大", "同上"),
    "pvalue_sigma_sum_exposed": c("露出した機会の、不確実性 σ の和", "買った機会の σ が、P（見積もりの偏り）に効くかを見るため"),
    "n_sim_iters": c("そのティックで simulate_ad_bidding を呼んだ回数（1 = やり直しなし）", "C5 の確認", "回"),
    "reward_first_iter": c("やり直しの前（1 回目）の購入数", "予算超過の取り消しで、購入がどれだけ減ったか", "件"),
    "n_overcost_agents_first": c("1 回目に、支払いが残り予算を超えた広告主の数", "やり直しの原因が、プレイヤーか他社か", "社"),
    "mp1_mean": c("2 位の入札額（枠 1 の支払い単価）の平均", "市場価格の水準（枠ごと）"),
    "mp2_mean": c("3 位の入札額（枠 2 の支払い単価）の平均", "同上"),
    "lwc_p10": c("4 位の入札額（枠 3 の支払い単価 = least winning cost）の 10% 点", "市場価格の分布"),
    "lwc_p50": c("同・中央値", "同上"),
    "lwc_p90": c("同・90% 点", "同上"),
    "n_pv_sold3": c("3 枠とも売れた機会の数", "売れ残りの量（入札者が減った時間帯）", "件"),
    "n_pv_sold0": c("1 枠も売れなかった機会の数", "同上", "件"),
    "n_exposed_all": c("全 48 社の露出の合計", "市場全体の量", "件"),
    "reward_all": c("全 48 社の購入数の合計", "同上", "件"),
    "bidding_seconds_all": c("全 48 社の bidding() の時間の合計", "ティックの時間の内訳", "秒"),
    "sim_seconds": c("simulate_ad_bidding の時間（やり直しを含む合計）", "同上", "秒"),
    "adjust_seconds": c("adjust_over_cost の時間", "同上", "秒"),
    "env_sort_seconds": c("環境の段：入札額の順位づけ", "シミュレータのどの段が重いか", "秒"),
    "env_slot_seconds": c("環境の段：枠の割り当て", "同上", "秒"),
    "env_cost_seconds": c("環境の段：支払い単価", "同上", "秒"),
    "env_exposure_seconds": c("環境の段：露出の抽選", "同上", "秒"),
    "env_values_seconds": c("環境の段：雑音を加えた確率（打ち切り正規分布）", "同上", "秒"),
    "env_conversion_seconds": c("環境の段：購入の抽選", "同上", "秒"),
    "env_unsold_seconds": c("環境の段：売れ残りの処理", "同上", "秒"),
    "tick_core_seconds": c("入札の開始から、記録の直前までの時間（記録を含まない）", "記録を除いたティックの時間", "秒"),
    "tick_cpu_seconds": c("そのティックの CPU 時間", "壁時計との差が、待ち", "秒"),
    "hook_seconds": c("記録（tick_hook）にかかった時間", "記録の重さ", "秒"),
    "ended_at_epoch": c("ティックが終わった時刻（UNIX 時刻）", "並列の run との重なり", "秒"),
})
COLUMNS["agents"]["columns"].update({
    "n_est": c("N_est：落札して露出した機会の、①の和（エピソードの合計）", "背景の 47 社についても、E・P・L を作れるようにするため", "件"),
    "n_real": c("N_real：同・②の和", "同上", "件"),
    "real_var": c("同・②×(1−②) の和", "同上"),
    "trunc_u1": c("雑音の打ち切りの乱数 u1（下側 −2×u1 標準偏差）。広告主 × エピソードで決まる", "C3 の確認。P の水準を、u1・u2 から予測できるかを見る（REP006 7 節 (3)）"),
    "trunc_u2": c("同・u2（上側 +2×u2 標準偏差）", "同上"),
    "trunc_seed": c("u1・u2 を作った乱数の種（hash((広告主, 0, エピソード)) + 1019 の下位 32 ビット）", "再現"),
    "budget_exhausted_tick": c("残り予算が min_remaining_budget を下回ったティック（下回らなければ −1）", "競合の脱落の時刻"),
    "bid_sum_exposed": c("露出した機会の入札額の和", "第二価格による割引（cost / これ）"),
    "n_bids_dropped": c("予算超過のやり直しで、0 にされた入札の数", "C5 の確認", "件"),
    "strategy_class": c("戦略のクラス名", "agent_name より確実に、手法で集計するため"),
})
COLUMNS["sim_iters"] = {
    "description": "1実行 × エピソード × ティック × simulate_ad_bidding の呼び出し（iter 0 = 1 回目、1 以上 = 予算超過のやり直し）。主キー (run_id, episode, tick, iter)。版 2 の run だけ。",
    "columns": {
        "run_id": c("runs.run_id", J), "episode": c("エピソード番号", J), "tick": c("ティック番号", J),
        "iter": c("呼び出しの番号（0 から）", "やり直しの何回目か"),
        "n_overcost_agents": c("この回に、支払いが残り予算を超えた広告主の数", "C5：やり直しが、いつ、何社で起きるか", "社"),
        "over_cost_ratio_max": c("(支払い − 残り予算) / 支払い の、48 社の最大（0 なら、この回で確定）", "同上"),
        "overcost_agents": c("超過した広告主の番号（JSON）", "同上"),
        "player_over_cost_ratio": c("プレイヤーの同じ値", "プレイヤーが原因のやり直しか"),
        "player_cost": c("この回のプレイヤーの支払い", "やり直しで、支払いがどう変わったか"),
        "player_reward": c("この回のプレイヤーの購入数", "やり直しで、購入がどう変わったか", "件"),
        "total_cost_all": c("この回の全 48 社の支払い", "同上"),
        "sim_seconds": c("この回の simulate_ad_bidding の時間", "時間の内訳", "秒"),
    },
}
COLUMNS["agent_ticks"] = {
    "description": "1実行 × エピソード × ティック × 広告主（48）。全員のティックごとの集計と、手法の内部状態。主キー (run_id, episode, tick, agent_index)。"
                   "原本は raw/agent_ticks.parquet（git 管理外）。記録の段 standard 以上の run だけ。DuckDB では view。",
    "columns": {
        "run_id": c("runs.run_id", J), "episode": c("エピソード番号", J), "tick": c("ティック番号", J),
        "agent_index": c("広告主の番号（0..47）", J),
        "is_player": c("プレイヤーか", "プレイヤーと背景の区別"),
        "did_bid": c("このティックで bidding() が呼ばれたか（予算が残っていたか）", "予算切れの検出"),
        "remaining_budget_before": c("入札前の残り予算", "競合の予算の残り方"),
        "alpha_eff": c("実効入札係数 = 入札額の和 / 推定価値の和", "全 48 社の α の時系列（プレイヤーの α との差が、勝敗を決める）"),
        "bid_mean": c("入札額の平均", "入札の水準"),
        "bid_nonzero_n": c("入札額が正の機会の数", "予算切れ・取り消しの検出", "件"),
        "pvalue_sum": c("推定価値の和", "alpha_eff の分母"),
        "pvalue_std": c("推定価値の標準偏差", "価値のばらつき"),
        "sigma_sum": c("不確実性 σ の和", "σ の水準"),
        "n_won": c("落札した数", "勝てた量", "件"), "n_slot1": c("枠 1 の落札", "枠の内訳", "件"),
        "n_slot2": c("枠 2 の落札", "同上", "件"), "n_slot3": c("枠 3 の落札", "同上", "件"),
        "n_exposed": c("露出した数", "支払い・購入が生じる単位", "件"),
        "cost": c("支払い", "予算の消化"), "reward": c("購入数", "成果", "件"),
        "bidding_seconds": c("bidding() の時間", "手法ごとの計算の重さ", "秒"),
        "state_raw": c("学習ベースの手法の入力状態（16 次元、正規化の前）。ルールベースは NULL", "方策が何を見て α を決めたか。学習データの状態の分布と比べるため"),
        "state_norm": c("同・正規化のあと（方策に渡した値）", "同上"),
        "internal_json": c("手法の内部状態（JSON）。PID：alpha・branch（up/down/keep/init）・last_tick_cost・low_ratio・high_ratio。"
                           "Online LP：table_rows・table_cpa・alpha_before_cap・alpha・capped。ABid：alpha・base_action・pvalue_mean。学習ベース：alpha",
                           "α が、なぜその値になったか（PID のどの分岐か、Online LP が上限に当たったか）を、あとから読むため"),
        **_TICK_AGENT_COMMON,
    },
}
_PV = {
    "run_id": c("runs.run_id", J), "episode": c("エピソード番号", J), "tick": c("ティック番号", J),
    "pv_index": c("そのティックの中での機会の番号（0 から）", "同じ番号の機会に、同じ乱数が当たるか（C6）を調べるため"),
    "pvalue": c("推定価値（①）。float32", "入札者の見積もり"),
    "sigma": c("推定価値の不確実性 σ。float32", "雑音の大きさ"),
    "value_real": c("雑音を加えた値（0〜1 に切る前）。②は clip(value_real, 0, 1)。float32", "環境の本当の購入確率。雑音 = (value_real − pvalue) / sigma"),
    "bid": c("入札額（予算超過の取り消しのあと）。float32", "入札"),
    "bid_before_adjust": c("入札額（取り消しの前）。bid が 0 でこれが正なら、取り消された入札", "C5 の確認"),
    "slot": c("得た枠（1〜3。0 = 落札せず）", "枠"),
    "price": c("支払い単価（1 つ下の順位の入札額）。露出しなければ払わない", "第二価格"),
    "exposure_draw": c("露出の抽選の結果（枠 3 の取り消しと、売れ残りの処理の前）", "枠 3 の取り消しが、どれだけ起きたか"),
    "is_exposed": c("露出したか（最終）", "支払い・購入が生じるか"),
    "conversion_draw": c("購入の抽選の結果（露出を掛ける前）", "落札しなかった機会でも、抽選の結果が分かる（反実仮想）"),
    "conversion": c("購入（= conversion_draw × is_exposed）", "成果"),
    "bid_rank": c("48 社の中での入札額の順位（1 = 最高。自分より高い入札の数 + 1）", "あと何位で落札できたか"),
    "top1_bid": c("その機会の 1 位の入札額", "競合の入札の上位（市場価格）"),
    "top2_bid": c("2 位の入札額（枠 1 の支払い単価）", "同上"),
    "top3_bid": c("3 位の入札額（枠 2 の支払い単価）", "同上"),
    "top4_bid": c("4 位の入札額（枠 3 の支払い単価。最低落札価格）", "同上"),
    "winner1": c("枠 1 を得た広告主の番号（−1 = 売れ残り）", "誰に負けたか"),
    "winner2": c("枠 2 を得た広告主の番号", "同上"),
    "winner3": c("枠 3 を得た広告主の番号", "同上"),
}
COLUMNS["pv_won"] = {
    "description": "プレイヤーの機会ごとの記録のうち、落札した機会と、予算超過で入札を取り消された機会。主キー (run_id, episode, tick, pv_index)。"
                   "原本は raw/pv_won.parquet（git 管理外）。記録の段 standard 以上。DuckDB では view。",
    "columns": dict(_PV),
}
COLUMNS["pv_all"] = {
    "description": "プレイヤーの機会ごとの記録（全機会。1 エピソード約 50 万行）。主キー (run_id, episode, tick, pv_index)。"
                   "原本は raw/pv_all.parquet（git 管理外）。記録の段 detail 以上。DuckDB では view。",
    "columns": dict(_PV),
}
COLUMNS["epl"] = {
    "description": "view。1実行 × エピソード × 広告主（48）の、REP006 の三つの指標（E・P・L）。agents と runs から作る。版 2 の run だけ。購入 0 の行は L・R が NULL。",
    "columns": {
        "run_id": c("runs.run_id", J), "episode": c("エピソード番号", J), "agent_index": c("広告主の番号", J),
        "is_player": c("プレイヤーか", "プレイヤーと背景の区別"),
        "strategy": c("プレイヤーの手法（runs.strategy）", "手法ごとの集計"),
        "strategy_class": c("その広告主の戦略のクラス名", "背景の広告主の手法ごとの集計"),
        "cpa_constraint": c("CPA 制約 C", "E と R の分母"), "cost": c("支払い（Cost）", "E の分子"),
        "reward": c("購入数（Conv）", "L の分母", "件"),
        "n_est": c("N_est", "E の分母、P の分子", "件"), "n_real": c("N_real", "P の分母、L の分子", "件"),
        "real_var": c("②×(1−②) の和", "抽選の分散"),
        "E": c("買い方 = cost / n_est / C", "REP006 2.8"), "P": c("見積もりの偏り = n_est / n_real", "同上"),
        "L": c("抽選 = n_real / reward（購入 0 なら NULL）", "同上"),
        "R": c("実績 CPA ÷ C = cost / reward / C（購入 0 なら NULL）。E × P × L に等しい", "同上"),
        "z": c("(reward − n_real) / sqrt(real_var)", "抽選の確認（REP006 集計5）"),
    },
}
COLUMNS["runs_newest"] = {
    "description": "view。同じ設定（config_key）× プレイヤー位置の run のうち、status = ok かつ github_dirty = false で、いちばん新しいもの 1 つ。列は runs と同じ。",
    "columns": {},
}


if __name__ == "__main__":
    (H / "columns.json").write_text(json.dumps(COLUMNS, ensure_ascii=False, indent=1), encoding="utf-8")
    print("wrote", H / "columns.json")
